---
- name: Apply common configuration to all nodes
  hosts: cluster_nodes
  become: true
  roles:
    - common

- name: Initialize control plane
  hosts: control_plane
  become: true
  roles:
    - control_plane

- name: Join workers
  hosts: workers
  become: true
  roles:
    - worker

- name: Build blog image
  hosts: localhost
  become: false
  roles:
    - build_blog

- name: Load blog image on all nodes
  hosts: cluster_nodes
  become: true
  roles:
    - load_blog_image

- name: Deploy Blog Application
  hosts: control_plane
  become: true
  roles:
    - deploy_blog

- name: Test High Availability
  hosts: control_plane
  become: true
  roles:
    - test_ha
